/*
 * @(#)SceneTest.java 1.0 29/12/2016
 *
 * Copyright (c) 2016, Fatec Jessen Vidal. All rights reserved. Fatec Jessen Vidal
 * proprietary/confidential. Use is subject to license terms.
 */
package br.gov.sp.fatec.mapskills.test.unit;

import static org.junit.Assert.assertEquals;

import java.util.ArrayList;
import java.util.List;

import org.junit.After;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.test.context.support.AnnotationConfigContextLoader;

import br.gov.sp.fatec.mapskills.application.MapSkillsException;
import br.gov.sp.fatec.mapskills.domain.scene.Alternative;
import br.gov.sp.fatec.mapskills.domain.scene.Question;
import br.gov.sp.fatec.mapskills.domain.scene.Scene;
import br.gov.sp.fatec.mapskills.domain.scene.SceneService;
import br.gov.sp.fatec.mapskills.test.unit.config.SpringContextConfigurationTest;
import br.gov.sp.fatec.mapskills.utils.SaveImageService;

@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(classes = SpringContextConfigurationTest.class, loader = AnnotationConfigContextLoader.class)
public class SceneTest extends MapSkillsTest {
	
	@Autowired
	private SceneService service;

	@After
	public void cleanTables() {
		super.cleanTables(service);
	}
	
	@Test
	public void save() {
		final int THEME_ID = 1;
		final int SKILL_ID = 1;
		final List<Alternative> alternatives = builderMockAlternatives();
		final Question question = new Question(alternatives, SKILL_ID);
		final Scene scene = new Scene("intro", "url:site", question, THEME_ID);
		service.save(scene);
	}
	
	@Test
	public void saveList() {
		final int THEME_ID = 1;
		final int SKILL_ID = 1;
		final List<Alternative> alternatives = builderMockAlternatives();
		final Question question = new Question(alternatives, SKILL_ID);
		final Scene scene1 = new Scene("texto 1", "/scenes/img001.png", null, THEME_ID);
		final Scene scene2 = new Scene("questão", "/scenes/img002.png", question, THEME_ID);
		final Scene scene3 = new Scene("texto 1", "/scenes/img003.png", null, THEME_ID);
		final List<Scene> scenes = new ArrayList<>(3);
		scenes.add(scene1);
		scenes.add(scene2);
		scenes.add(scene3);
		service.save(scenes);
			
		assertEquals(3, service.findAllByGameThemeId(THEME_ID).size());
	}
	
	@Test
	public void nextIndex() {		
		final int index = service.nextIndex(1);
		assertEquals(0, index);
		
		final Scene scene = new Scene("intro", "url:site", null, 1);
		service.save(scene);
		
		final int nextIndex = service.nextIndex(1);
		
		assertEquals(1, nextIndex);
	}

	@Test
	public void update() {
		final int THEME_ID = 1;
		final int SKILL_ID = 1;
		final List<Alternative> alternatives = builderMockAlternatives();
		final Question question = new Question(alternatives, SKILL_ID);
		final Scene sceneSave2 = new Scene("textoB", "/scenes/img005.png", question, THEME_ID);
		service.save(sceneSave2);
		
		final Scene sceneUpdate = new Scene("TextoA", "/images/img001.png", null, THEME_ID);
		sceneUpdate.setId(sceneSave2.getId());
		service.save(sceneUpdate);

	}
	
	@Autowired
	private SaveImageService saveImage;
		
	@Test
	public void saveImage() throws MapSkillsException {
		final String base64 = getFileBase64();
		final String filename = "IMAGE_SAVED.png";
		saveImage.save(base64, filename);
	}
	
	private String getFileBase64() {
		return "iVBORw0KGgoAAAANSUhEUgAAAj4AAAIWCAYAAABXzYf3AAAACXBIWXMAAAsTAAALEwEA" +
				"mpwYAAABOWlDQ1BQaG90b3Nob3AgSUNDIHByb2ZpbGUAAHjarZGxSsNQFIa/G0XFoVYI" +
				"4uBwJ1FQbNXBjElbiiBYq0OSrUlDldIk3NyqfQhHtw4u7j6Bk6PgoPgEvoHi1MEhSHAS" +
				"wW/6zs/hcOAHo2LXnYZRhkGsVbvpSNfz5ewTM0wBQCfMUrvVOgCIkzjiJwI+XxEAz5t2" +
				"3WnwN+bDVGlgAmx3oywEUQH6FzrVIMaAGfRTDeIOMNVJuwbiASj1cn8BSkHub0BJuZ4P" +
				"4gMwe67ngzEHmEHuK4Cpo0sNUEvSkTrrnWpZtSxL2t0kiOTxKNPRIJP7cZioNFEdHXWB" +
				"/D8AFvPFdtORa1XL2lvnn3E9X+b2foQAxNJjkRWEQ3X+3YWx8/tc3Bgvw+EtTE+KbPcK" +
				"bjZg4brIVqtQ3oL78RfCs0/+HAmzJwAAPFdpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAA" +
				"ADw/eHBhY2tldCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlk" +
				"Ij8+Cjx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFk" +
				"b2JlIFhNUCBDb3JlIDUuNS1jMDE0IDc5LjE1MTQ4MSwgMjAxMy8wMy8xMy0xMjowOTox" +
				"NSAgICAgICAgIj4KICAgPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9y" +
				"Zy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KICAgICAgPHJkZjpEZXNjcmlwdGlv" +
				"biByZGY6YWJvdXQ9IiIKICAgICAgICAgICAgeG1sbnM6eG1wTU09Imh0dHA6Ly9ucy5h" +
				"ZG9iZS5jb20veGFwLzEuMC9tbS8iCiAgICAgICAgICAgIHhtbG5zOnN0UmVmPSJodHRw" +
				"Oi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvc1R5cGUvUmVzb3VyY2VSZWYjIgogICAgICAg" +
				"ICAgICB4bWxuczpzdEV2dD0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL3NUeXBl" +
				"L1Jlc291cmNlRXZlbnQjIgogICAgICAgICAgICB4bWxuczp4bXA9Imh0dHA6Ly9ucy5h" +
				"ZG9iZS5jb20veGFwLzEuMC8iCiAgICAgICAgICAgIHhtbG5zOmRjPSJodHRwOi8vcHVy" +
				"bC5vcmcvZGMvZWxlbWVudHMvMS4xLyIKICAgICAgICAgICAgeG1sbnM6cGhvdG9zaG9w" +
				"PSJodHRwOi8vbnMuYWRvYmUuY29tL3Bob3Rvc2hvcC8xLjAvIgogICAgICAgICAgICB4" +
				"bWxuczp0aWZmPSJodHRwOi8vbnMuYWRvYmUuY29tL3RpZmYvMS4wLyIKICAgICAgICAg" +
				"ICAgeG1sbnM6ZXhpZj0iaHR0cDovL25zLmFkb2JlLmNvbS9leGlmLzEuMC8iPgogICAg" +
				"ICAgICA8eG1wTU06T3JpZ2luYWxEb2N1bWVudElEPnhtcC5kaWQ6MDU4MDExNzQwNzIw" +
				"NjgxMTgwODM5MjNCREVDMzg5ODQ8L3htcE1NOk9yaWdpbmFsRG9jdW1lbnRJRD4KICAg" +
				"ICAgICAgPHhtcE1NOkRvY3VtZW50SUQ+eG1wLmRpZDo3RjM0Mzc5MUE3NDkxMUUyQjND" +
				"RTg5RDNFQjJEOEE0QTwveG1wTU06RG9jdW1lbnRJRD4KICAgICAgICAgPHhtcE1NOklu" +
				"c3RhbmNlSUQ+eG1wLmlpZDo1MTRhZTZlOS1hOGQ0LTdjNGYtYjE0ZS00ZDhlODY4MmVk" +
				"NmY8L3htcE1NOkluc3RhbmNlSUQ+CiAgICAgICAgIDx4bXBNTTpEZXJpdmVkRnJvbSBy" +
				"ZGY6cGFyc2VUeXBlPSJSZXNvdXJjZSI+CiAgICAgICAgICAgIDxzdFJlZjppbnN0YW5j" +
				"ZUlEPnhtcC5paWQ6MDc4MDExNzQwNzIwNjgxMTgwODM5MjNCREVDMzg5ODQ8L3N0UmVm" +
				"Omluc3RhbmNlSUQ+CiAgICAgICAgICAgIDxzdFJlZjpkb2N1bWVudElEPnhtcC5kaWQ6" +
				"MDU4MDExNzQwNzIwNjgxMTgwODM5MjNCREVDMzg5ODQ8L3N0UmVmOmRvY3VtZW50SUQ+" +
				"CiAgICAgICAgIDwveG1wTU06RGVyaXZlZEZyb20+CiAgICAgICAgIDx4bXBNTTpIaXN0" +
				"b3J5PgogICAgICAgICAgICA8cmRmOlNlcT4KICAgICAgICAgICAgICAgPHJkZjpsaSBy" +
				"ZGY6cGFyc2VUeXBlPSJSZXNvdXJjZSI+CiAgICAgICAgICAgICAgICAgIDxzdEV2dDph" +
				"Y3Rpb24+c2F2ZWQ8L3N0RXZ0OmFjdGlvbj4KICAgICAgICAgICAgICAgICAgPHN0RXZ0" +
				"Omluc3RhbmNlSUQ+eG1wLmlpZDo2NDNjOWMxMy04YWZjLTFkNGYtOTBmZi03ZmMxYTYz" +
				"ZmU3N2M8L3N0RXZ0Omluc3RhbmNlSUQ+CiAgICAgICAgICAgICAgICAgIDxzdEV2dDp3" +
				"aGVuPjIwMTQtMDctMjRUMTE6MTA6NDgrMDI6MDA8L3N0RXZ0OndoZW4+CiAgICAgICAg" +
				"ICAgICAgICAgIDxzdEV2dDpzb2Z0d2FyZUFnZW50PkFkb2JlIFBob3Rvc2hvcCBDQyAo" +
				"V2luZG93cyk8L3N0RXZ0OnNvZnR3YXJlQWdlbnQ+CiAgICAgICAgICAgICAgICAgIDxz" +
				"dEV2dDpjaGFuZ2VkPi88L3N0RXZ0OmNoYW5nZWQ+CiAgICAgICAgICAgICAgIDwvcmRm" +
				"OmxpPgogICAgICAgICAgICAgICA8cmRmOmxpIHJkZjpwYXJzZVR5cGU9IlJlc291cmNl" +
				"Ij4KICAgICAgICAgICAgICAgICAgPHN0RXZ0OmFjdGlvbj5zYXZlZDwvc3RFdnQ6YWN0" +
				"aW9uPgogICAgICAgICAgICAgICAgICA8c3RFdnQ6aW5zdGFuY2VJRD54bXAuaWlkOjUx" +
				"NGFlNmU5LWE4ZDQtN2M0Zi1iMTRlLTRkOGU4NjgyZWQ2Zjwvc3RFdnQ6aW5zdGFuY2VJ" +
				"RD4KICAgICAgICAgICAgICAgICAgPHN0RXZ0OndoZW4+MjAxNC0wNy0yNFQxMToxMDo0" +
				"OCswMjowMDwvc3RFdnQ6d2hlbj4KICAgICAgICAgICAgICAgICAgPHN0RXZ0OnNvZnR3" +
				"YXJlQWdlbnQ+QWRvYmUgUGhvdG9zaG9wIENDIChXaW5kb3dzKTwvc3RFdnQ6c29mdHdh" +
				"cmVBZ2VudD4KICAgICAgICAgICAgICAgICAgPHN0RXZ0OmNoYW5nZWQ+Lzwvc3RFdnQ6" +
				"Y2hhbmdlZD4KICAgICAgICAgICAgICAgPC9yZGY6bGk+CiAgICAgICAgICAgIDwvcmRm" +
				"OlNlcT4KICAgICAgICAgPC94bXBNTTpIaXN0b3J5PgogICAgICAgICA8eG1wOkNyZWF0" +
				"b3JUb29sPkFkb2JlIFBob3Rvc2hvcCBDQyAoV2luZG93cyk8L3htcDpDcmVhdG9yVG9v" +
				"bD4KICAgICAgICAgPHhtcDpDcmVhdGVEYXRlPjIwMTQtMDctMjRUMTA6NTk6NTgrMDI6" +
				"MDA8L3htcDpDcmVhdGVEYXRlPgogICAgICAgICA8eG1wOk1vZGlmeURhdGU+MjAxNC0w" +
				"Ny0yNFQxMToxMDo0OCswMjowMDwveG1wOk1vZGlmeURhdGU+CiAgICAgICAgIDx4bXA6" +
				"TWV0YWRhdGFEYXRlPjIwMTQtMDctMjRUMTE6MTA6NDgrMDI6MDA8L3htcDpNZXRhZGF0" +
				"YURhdGU+CiAgICAgICAgIDxkYzpmb3JtYXQ+aW1hZ2UvcG5nPC9kYzpmb3JtYXQ+CiAg" +
				"ICAgICAgIDxwaG90b3Nob3A6Q29sb3JNb2RlPjM8L3Bob3Rvc2hvcDpDb2xvck1vZGU+" +
				"CiAgICAgICAgIDxwaG90b3Nob3A6RG9jdW1lbnRBbmNlc3RvcnM+CiAgICAgICAgICAg" +
				"IDxyZGY6QmFnPgogICAgICAgICAgICAgICA8cmRmOmxpPnhtcC5kaWQ6N0YzNDM3OTFB" +
				"NzQ5MTFFMkIzQ0U4OUQzRUIyRDhBNEE8L3JkZjpsaT4KICAgICAgICAgICAgPC9yZGY6" +
				"QmFnPgogICAgICAgICA8L3Bob3Rvc2hvcDpEb2N1bWVudEFuY2VzdG9ycz4KICAgICAg" +
				"ICAgPHBob3Rvc2hvcDpJQ0NQcm9maWxlPkFkb2JlIFJHQiAoMTk5OCk8L3Bob3Rvc2hv" +
				"cDpJQ0NQcm9maWxlPgogICAgICAgICA8dGlmZjpPcmllbnRhdGlvbj4xPC90aWZmOk9y" +
				"aWVudGF0aW9uPgogICAgICAgICA8dGlmZjpYUmVzb2x1dGlvbj43MjAwMDAvMTAwMDA8" +
				"L3RpZmY6WFJlc29sdXRpb24+CiAgICAgICAgIDx0aWZmOllSZXNvbHV0aW9uPjcyMDAw" +
				"MC8xMDAwMDwvdGlmZjpZUmVzb2x1dGlvbj4KICAgICAgICAgPHRpZmY6UmVzb2x1dGlv" +
				"blVuaXQ+MjwvdGlmZjpSZXNvbHV0aW9uVW5pdD4KICAgICAgICAgPGV4aWY6Q29sb3JT" +
				"cGFjZT42NTUzNTwvZXhpZjpDb2xvclNwYWNlPgogICAgICAgICA8ZXhpZjpQaXhlbFhE" +
				"aW1lbnNpb24+NTc0PC9leGlmOlBpeGVsWERpbWVuc2lvbj4KICAgICAgICAgPGV4aWY6" +
				"UGl4ZWxZRGltZW5zaW9uPjUzNDwvZXhpZjpQaXhlbFlEaW1lbnNpb24+CiAgICAgIDwv" +
				"cmRmOkRlc2NyaXB0aW9uPgogICA8L3JkZjpSREY+CjwveDp4bXBtZXRhPgogICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"IAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAK" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAog" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"IAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAK" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAog" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAg" +
				"ICAgIAo8P3hwYWNrZXQgZW5kPSJ3Ij8+Sq2kZAAAACBjSFJNAAB6JQAAgIMAAPn/AACA" +
				"6AAAUggAARVYAAA6lwAAF2/XWh+QAABTBUlEQVR42uzdf5xVdYH/8ReII8LwQwiZaQQS" +
				"R1JMwggKI0KSpLTJWvoB2Fd3NdDYtsTCdjNcydowxbZdMtwsakGz2BVZLQoXyUgSQmcx" +
				"0XBEHaRhQn7PII44fP84n0k0fs3MOfeec+/r+XjcB0r2ufd+zo/P+37O50eHAwcOIEmS" +
				"VAw6WgWSJMngI0mSZPCRJEky+EiSJBl8JEmSDD6SJEkGH0mSJIOPJEmSwUeSJMngI0mS" +
				"ZPCRJEkGH0mSJIOPJEmSwUeSJMngI0mSZPCRJEky+EiSJBl8JEmSDD6SJEkGH0mSJIOP" +
				"JEky+EiSJBl8JEmSDD6SJEmZ0imNH2rYTY94ZKR06Az0AcqANwE9D/E6CSgFjg//3gno" +
				"DpwAdDmorA7hf3+jncCBg/59L/AysBvYH/73V4AGYEf49ze+XgS2AFuBfR42Kf/WzniX" +
				"wUdSanQIYaYfcEr4s3/45zcfFHZ65OCzvDEMndTO8nYdFIL+BLwA1AKbwj9vCv/7AU8D" +
				"qfgYfKTCdRxwKlAJnPaGPwcS9cgUoh7h9dYj/DcvAxuBZ4Ca8Gr552eBVz19JIOPpPQG" +
				"nNOBs4Azwp9nhtcJVs8hnXBQHR0qFD0ZXk8AT4U/nzYQSQYfSbnVBTgbGAqcE/48m9eP" +
				"pVH7Q9HQ8DrYXuBxoBp4LPz5ePh7SQYfSe3UkagH513h9W6i3hyv2/yFzpZj0WI/UW/Q" +
				"74BHwuspoNnqkgw+ko7sxBBuRgOjgOHkZnCx2ncPfXt4TQ1/twtYA6wEHgphyF4hyeAj" +
				"Fb1S4H0h5IwOQed4qyXzegDnhxdEU/HXhBC0Evg10dR8SQYfqeCvtxEHNYojvQaLwvHA" +
				"ueEF0eOxVcAD4bU6/J0kg4+UeacAFwIfBM4jWthP3nffG143EC3U+CCwFLiPaK0hSQYf" +
				"KROOI+rV+XAIO0OtEh1Fd+Aj4XUb0WyxXwD/Q9Qb5BR6yeAjpcoJwPuBj4bGq49VonYY" +
				"Gl7/SLT69L3APcD/Eq0xJMngI+VcF6IenY8BF+EjLCWjD3BFeO0mehT230Q9Qs4Ukww+" +
				"UqJKgAuAiUAV0NUqUQ51ByaFVyOwBLgL+CXQZPVIBh8pDh2JppxPIurd6WWVKAW6hgA+" +
				"EdhO1At0J9FUeRdPlAw+UqudAVwGfJpot3IprXrx2uOwPwH/CcwnWkFa0iF+zUqK9ACm" +
				"AA8TbVB5raFHGfPmcN4+Gc7jKbj6t2Twkd5gZPiFXAfMC/8uFcJ5PS+c1/M9ryWDj4pb" +
				"D+CzwP+FX8aXEu2VJRWaE8P5/XA43z+LvUAqYo7xUbEZAvw90aDQUqsjdruItl/YRTTT" +
				"qPGg/20ncOAQ/58OQM+D/r0r0Qy6HuEeZSMd7/k/F5hNNCPs34F1VosMPlJhOY5occG/" +
				"J5qhpaPbS7R1wtbw2gLUh3/eFkLMG1/7Evw8nUM4euOrN9FaN32BsvDPfYi2CuniYTys" +
				"UuAz4fXrEIDuwVWiZfCRMq070UyXzwFvsTpe50VgY3g9C2wKr9oQeLan7PPuC+FrSyv+" +
				"P71CAOoP9Auv04CBQCWv72UqZu8Lr+eAfwO+T7RYomTwkTKiHPg8cBXFvaLy/hBsniCa" +
				"2vwH4Onw2lkE3397eB3uUU7vEIQqgbOAM8OfA4v03vgW4BbgeqI9w75DND1eMvhIKfVW" +
				"4EvAJUT7ZxWTrUSbWz4W/mwJO67oe3jbwmv1G/6+hGgdp7OI9sw6J/xZLHuwdSeaEv8F" +
				"YAHwLeCPni4y+EjpMQy4jmgbiWKYqfgisCa81oagU+tpEJsmol6idUQDgFv0CyFoGDA8" +
				"vN5UwPVwAnA58LdE22PcGM43yeAj5ckIYCbwIaKZQYXoANFidA8Bq4DfARs89HnRMg5q" +
				"yUF/Nwh4N9EaOaOJHpcV2rnYEbgY+Ajwc+BrwCOeDjL4SLlzbgg8FxTgd2sm6sF5iGi2" +
				"zW+JHmMpnTaE14/Dv/cB3kM0WHg08HaiWYWFoANwYXj9EphFtDaQZPCREvJO4OvABwrs" +
				"e20ElgEPAMtJ34wqHbutwOLwgmhm2VjgfGAc0cDpQnBBeP0K+Arwew+9DD5SfM4CbiDa" +
				"Hb0QHiM0hpCzNDQcGz3EBWs7sCi8CMHnA8B44P1kfxHND4RAdw9RL+wTHnKlnVtWKM0G" +
				"Ej1CWAf8TcZDz/NEK+aOJxoQezHwPUNP0dkYjvvFRI/FLgjnxfMZ/k4dwo+SdeF6Hehh" +
				"lsFHap2TgJuJBvV+OsPn6ZPAN4ge0b2FaOXoX5LsCsfKjn1EPX5/H86Plke5T2a4Pfl0" +
				"+Pw3Ez3mkww+0hGUANeEX8XXhH/Pmv8DvgoMDq+v4BRgHZu1RMsyHHzu/F+Gr+NnMnwd" +
				"y+AjJaoD0aahT4Vfij0z9vlriNY4aVnw7sYM/2pXOrT0Fg4N59WN4TzLkp7hen4qXN8d" +
				"PKwy+EjRgnAPAncCp2boc/8Z+DbwLuB0ol6e9R5OJWB9OL9OD+fbt8P5lxWnhut7Rbje" +
				"JYOPitKbgO8STYPNyo7prwD3Eg1MPQW4mr/e7kBK0upw3p0SzsN7w3mZBaPD9f5dCnvF" +
				"axl8pNc5Dvgs0UaZV2XkHPwj0ViFLDY2KkxvDOHTiR4pZaHNuSpc/5/FJVVk8FGBG060" +
				"1P1c0j+Opwm4m2jxuTOBOWTr8YKKx5+BW4kGRJ8H/AR4OeWfuWe4DzwS7guSwUcFpSfw" +
				"70T7TA1L+Wd9HvhHog0pP0U0/uiAh1AZcIBoHM1EoD/wZdK/PtA7wn3h38nepAYZfKRD" +
				"+hTR4MxpKT/fHgI+DpwGfBN7d5RtfwZmh/N5AtG+b2luh6aF+8SnPHQy+CirTgHuA+4C" +
				"ylP6GV8Gfhh+db6PaFuBVz10KiCvAv8FjAnn+Q9J72Ow8nC/uC/cPySDjzKhA3Al0Z49" +
				"F6b0M+4Ov4YHAn8HPOZhUxF4LJzvp4bzf3dKP+eF4f5xFa79I4OPUq6SaHfx24DuKfx8" +
				"fwJmEI3f+XL4d6nY1IXzv1+4HtJ4HXQnmva+PNxXJIOPUqUD8DmiTQrHpPDzPQdMDb90" +
				"v5XiX7pSLu0O18Op4fp4LoWfcUy4r/wD9v7I4KOUGAA8AHwHODFln+0Z4HJgEHA70RR1" +
				"Sa/XFK6PQUSPwp5J2ec7EfjXcJ8Z4OGSwUf5dCnRJopjU/a5ng6f7QzgB7jYoHQsXiEa" +
				"/HxGuH7StjfYWKLen0s9VDL4KNf6AIuB+UCPFH2uWuAKooXcfgzs91BJrbY/XD9nEj0C" +
				"eyFFn617uO8sDvchyeCjxJ1P1MvzkRR9pq3AF4g2cbzDwCPFFoBaHoFdHa6ztPhIuA+d" +
				"72GSwUdJOR64Cfgl6VmXpxH4OtG09H/FMTxSEl4i2hF+YLjeGlPyucrD/eimcH+SDD6K" +
				"zenAw8CXUnLONBON3TkduA5o8BBJiWsI19vp4fprTkkb9qVwfzrdQ6Rj4c64OpqJRN3d" +
				"pSn5PEuJ1h553EOTTrPHlw8DqG/YX1Hf8EoZwJ8b9pfVN+xvc09h39JOdSeXdtoCUFpy" +
				"3J6BvUo2AJzWq2TDhDuf32Ot51Qd0WzJW4mmw49PwWd6J/Ao0eKpCz1EMvioLU4Abgb+" +
				"PiWfp4ZonMF9Hpp0hJuWYPP4ln3nNDQ1d9u4vWkQwLVL6yB3O26vARjYq2RDaUnHPWeX" +
				"dX6sJRgZihL3B+CDwEUhBOV7ocFSYAFwLjCd9O9QrzzpcOBA+jaeHnbTIx6Z/DoV+Gn4" +
				"FZVvDcA3gFtwDE/OLZo0oNsz25sGrdvy0rCN25sGbdzedPpBPTfDU/7x1/Qt7VTXt7TT" +
				"n84u6/zYab1O2DCkrPNaw1AiSkLY+Arp6B3+PfAJ4FkPTf6snfEug4/BJxM+QjRdtGcK" +
				"PsudwBeJutaVA/Mn9KtYt2XfsMe3vDT0mSjoDMpAwGl1GBpS1nnt2WUnVg8p67z2skWb" +
				"NnvkY1NO9Phrcgo+y07gMuBeD4vBx+CjQ+kIzAL+ifwvDb8B+Czwvx6W5M0c23fMui0v" +
				"DVtVu3d06M0ZXkRf/y9BaGT/rg/ZIxSb9wNzgbfm+XMcIOoxnkk6BmMbfAw+Bp+U6Ek0" +
				"IPBDef4cLwHfJNo52ufzCWnp1VlV2zh6Ve3e0eGvh1szURBqCUEj+3d5yN6gdikh2gz1" +
				"y+R/O5tfAJOIeoFk8DH4FLmzgf8m/wMTlxOtElvjIYnfokkDui2rabhoWc2eCwvw8VVi" +
				"IWhgr5IN4yq73W8IapdK4HtEvUD5VAN8DGeEGnwMPkXtY8CPyO9gxJ1E43h+QNQtrRhN" +
				"H9Wn6qCeHcNOO0LQkLLOa8+v7PaLc/t3edDHYa1va4g2QL2Z/I4fbCDa6+u/PSQGH4NP" +
				"8d2E/hG4kfyO51lCNJbHX9IxmltVMWjx+l2ferh273mNTc1dDTzx6lrSccW5/bs8ePHg" +
				"Hj+ZtmTzBmukVd4MfJf8bnlzgGghxn/xx5bBx+BTHDoD/wFcksfPsI1ofaCfeDjiM31U" +
				"n6oHavZ8cN2WfcMMOzmxZmCvkg0XD+7xU3uBWu1TwL8Bb8rjZ1hItKnxPg+HwcfgU7j6" +
				"AvcAI/P4Ge4HPoNT1GOxaNKAbves3zXxgZqGC4twRlZqdC3puOLiwd3vGlfZ7X7HAh2z" +
				"8vAj7MI8foZVwEeBeg+HwcfgU3jOCqFjQJ7efw/RAmff91C03/wJ/SoWr9/1qWU1DRc1" +
				"NjWPsUZSY824ytL7Jg896Q4D0DFr2f6iW57e//kQvp7wUBh8DD6FYwzRYL6T8vT+vyEa" +
				"UOgqqjEEnoXVOy5fVtNwEfbuGIAKx6lEEy3em6f330E02WOFh8LgY/DJvknAD4nW1Mi1" +
				"/USLIn4DeNVDYeAxAOkIjiNaQHUm+dlHsgn4W6IV42XwMfhk1JdD6MjHzK3niJatf9jD" +
				"0HYtY3gWr9890Uda2Q9AU0f0vtVB0Ed1LtHA47fk4b0PEO039i8eBoOPwSdbOgLfAabl" +
				"6f1/AlwJ7PJQtN3UEb0nLqjeMcXAUzhaBkF/dHCPuwxAR9SDaNHDT+Xp/ecC/4DbXBRk" +
				"8OnooSk4JcCCPIWefUSrL0809LTd7PHlw/qWdrp33uptVxt6CktjU/OYhdU7501bsnnB" +
				"zLF9PbaHtyvcR6aSn+nm08J9tMRDUZg9AyqgH5REOxFPzMN7P000Tf52D0PbzJ/Qr2Jk" +
				"/y43X7u07rb6hv1VOJanYNU37K+atbz+piFlnW+bP6FfhTVyWLeH+8rTeXjviUSLrHb1" +
				"MBh8lE69gAeA8Xl4758B7wSqPQxtM3VE74nTlmxesKp27zUGnqIxfN2WfVdetmjTPZOH" +
				"9pxidRxWdbi//CwP731BuK/28jAYfJQufYFfA+/O8fvuJ9pn6xPAbg9D682tqhg0sFfJ" +
				"Ah9rFXcAWli984q+pZ3unT2+fJjVcUi7w33mi+G+k0vvDvfXMg9DYXBwc/ZVAP8LvDXH" +
				"77uVaODhcg9B20we2nPKwuqdV2APj16z5uLB3e++ZOhJtzv4+bDGEk2g6JPj9/0j0Q7z" +
				"LktwjBzcrCS8hWhxwFyHnkdDY23oaYOWXh5Djw5h+OL1u2+etmTzgrlVFYOsjkNaTvTo" +
				"69Ecv+9bw/32LR6CbDP4ZNcgou7XU3P8vguA9xAt865Wmjqi98QZS+vmbdzeNNnQo8Op" +
				"b9hfNW3J5gWO/Tms2nAfWpDj9z013HcNpQYf5eGXxwqgfw7fsxn4R+DTuJtxqy2aNKDb" +
				"yP5dbnYsj1ph+MLqnVcMKet826JJA7pZHX9lX7gf/SO5XW+nf7j/vtVDYPBRbpxO1NVb" +
				"nsP3bAD+Bvim1d96c6sqBjljS20NP+u27Lvy0kWbljjw+bC+Ge5PDTl8z/JwHz7d6jf4" +
				"KFmV4WJ7cw7fs5Zo48DFVn/rTR/Vp2raks0Lwro8Ups0NjWPuXZp3W0++jqsxeE+VZvD" +
				"93xzuB9XWv0GHyXjNOBB4JQcvuejwLtwfZ42GVdZOnPOyq3XYS+P4jF8YfXOK0b273Kz" +
				"j74OqTrcr9bm8D1PCffl06x+g4/iNSD8sshl6Pk58D5gi9XfOosmDeg2sFfJAndSVxLh" +
				"Z1Xt3mtmLK27zVlfh7QFGBPuX7kMP8vDfVoGH8WgjGjl0FwOZP4P4CPk9pl5QWgZz+Os" +
				"LSVp4/amyTOW1s0z/BxSQ7h/5XL7nP7hPu0ihwYftVMv4Ffk7hnyAeCrwBRyvzpq5s0e" +
				"Xz5sxtK6eY7nUS40NjWPmbZk84Lpo/p4vv21/UQbnF4X7mu5UBnu172tfoOP2qYbUXft" +
				"2Tl6v1dD4LnRqm+96aP6VF27tO42p6orx4bPWbn1uqkjek+0Kg7p68Bnwv0tF84G7ge6" +
				"W/UGH7VOF6JZCrla7/tlon1wvm/Vt97UEb0nOohZ+Qw/81Zvu3pcZelMq+KQ7gA+BryU" +
				"o/d7F3BPuI/L4KNjcBxwF9F+NLmwB/gg8N9WfeuNqyydOW/1tqsNPcp3+FlW03CR4eew" +
				"loT7XK42Ux4b7uPHWfUGHx3dvwG5ema/DTiPaDqm2hB6nLklw09m/DoEkm05er+qcD+X" +
				"wUdH8GXgqhy9V30IPWutdkOPCiv8uM3FYa0lmu5en6P3uyrc12Xw0WEukG/k6L02h4v/" +
				"cavd0KPCCz/rtuy7csbSOsPPof0h3P825+j9/iWHP2hl8MmMli7RDjl4r+eA0cBTVruh" +
				"R4Vr4/amybes3Hq9NXFIT4X74HM5er9cDmGQwSf1zgZ+TG4GwT1LtBrzRqvd0KPCt6p2" +
				"72jH/Bw+G4b74bM5eK/jgP8kd8uTyOCTWqcQrdXTIwfv9TzRmJ5aq93Qo6LhgOcjqw33" +
				"xedz8F7dw/3+FKvd4FOsWtbqOaXALu6CM31UnypDjww/BSuXPwpPAe7FNX4MPkWoZa2e" +
				"YTl4rxeIpnA+a7W3LfS4OKEKJfy4vcVhPRvCzws5eK934Bo/Bp8idCO5Gej253AxP2OV" +
				"t97cqopBhh4VUviZs3LrdYafw9oY7pe5mOpeRbSdhgw+ReFTwLU5eJ8dwPlAjVXettAz" +
				"Y2ndPEOPCi38zFu97Wp3dT+sGmBcuH8mbQbgHmsGn4L3DqJ9Y5Kett5AtDy76/S0waJJ" +
				"A7rdsnLrTDccVSFqbGoeM2Np3bz5E/pVWBuH9Hi4f+5J+H06EO2POMwqN/gUqj7kZlDb" +
				"S8BHgEes8raZtbz+po3bmyZbEyrk8DNref1sFzg8rEeAi0l+Y9OWSS4nW+UGn0JTQrQJ" +
				"aNIzuF4lepS23Cpvm4sHd79m3ZZ9/gJTwdu4vWly2GBXh7Y83E9fTfh9TgH+K7QTMvgU" +
				"jNnAqBy8z+eIdiFWG0wf1adq8frdn8RxPSoSy2oaLpo6orfjTA5vSbivJm1UaCdk8CkI" +
				"nwC+kIP3uRG4zepum7lVFYPCr19Dj4qJg52P7jZgVg7e5wvAJ61ug0/WnUk0mDkXF+ZX" +
				"re62cTCzij38zFhaN8/xPkd0fY5+WH4fGGx1G3yyqhvRuJ7ShN8nV12xBWtB9Y4pDmZW" +
				"MWtsah7jhqZHlYuhBKVE4326W90GnyyaB5yR8Hs8Dvw/kh98V7Bmju07JozrkYraqtq9" +
				"ox3vc0SvAp8m+WVCzgC+Z3UbfLLmMyS/MNULwIeAXVZ324RHXNfjuB4JYPiC6h1THO9z" +
				"RLvDfTfprS0mAlOsboNPVpwFfDvh99hLtMbEC1Z3281aXn+T43qk14RHXm5mevQfnR8J" +
				"9+Ek3RraExl8Uq0LcDfJLlJ4AJgErLW6227qiN4TXa9H+msbtzcNmjy0p70NR/ZouA8f" +
				"SLg9+Snu5G7wSbnv5CChX0+0ArTaaP6EfhULqndMwUdc0qEMX1i98wofeR3VveF+nKTB" +
				"oV2RwSeVJgCXJ/wei4jW61E7zFu97WofcUlHDj8+8jomN4b7cpIuD+2LDD6pUk40iytJ" +
				"64BLSbZrteDNHNt3zKravaOtCenINm5vGuQsr6M6EO7L65L+vQa4qazBJzU6APOBXgm+" +
				"x4vkZjBdQXMWl9QqwxdU75jiLu5HtReoCvfppPQCfhDaGxl88u4fgA8kWP6rwCXAc1Z1" +
				"+yyo3jHFR1zSsWtsah7jRqbH5HlgMsmuqfaB0N7I4JNXbwO+mfB73AD80qpun/kT+lW4" +
				"UKHUeqtq946ePb7cGZBH96twv07SN0O7I4NPXnQiesTVOcH3uB8HM8dizsqt1+EjLqkt" +
				"hs9xoPOxujHct5PSObQ7naxqg08+zACS/BW0kWh5dAczt9Ps8eXDXLNHarv6hv3l00f1" +
				"qbImjuoA0dCEjQm+x7DQ/sjgk1NnA0n+AmoCPgnssKrbL/xatbdHarvh81Zvu9od3I/J" +
				"znD/bkrwPa4P7ZAMPjnRCfghcEKC7/Fl4PdWdftNH9Wnqr5hf7k1IbVPY1PzmHvW73J6" +
				"+7H5fbiPJ6UktEM+8jL45ETSj7j+h+T3+ioaC6t3XI69PVIsFq/fPdFen2P27XA/T8ow" +
				"4Fqr2eCTtEHAVxMs/wXgb3FcTywmD+05xd4eKT72+rTKgXA/T3Iz6a8Cb7WqDT5J6QDc" +
				"TnKzuFrW69lmVbffokkDui1ev3si9vZIsbLXp1W2hft6Uuv7nEC0qrMLGxp8EvF3wPsS" +
				"LP9bwK+t5njcs37XRBcrlOJnr0+r/Trc35PyvtA+yeATq5OBmxIsfy3J7/JbVB6oabjQ" +
				"WpCSYa9Pq10f7vNJuSm0UzL4xOZWktuL6yWirtAmqzkezuSSkmWvT6s1Af8v3O+T0Asn" +
				"xRh8YnQeMCnB8mcAT1nN8XEml5Q8e31abT3JLjw4MbRXMvi0y/HA3ATL/9+Eyy86M8f2" +
				"HWNvj5S8xqbmMQ/X7rWhbZ254b6fZPnHW80Gn/b4PHBmQmU3AJ/Bqesx/wrd9Uns7ZFy" +
				"IvSu6tgdCPf9hoTKPzO0WzL4tEkFyQ44ngE8azXHZ/6EfhXuySXlTn3D/vKZY/uOsSZa" +
				"5VmSfeR1fWi/ZPBptZuB0oTK/l/ge1ZxIr8+7e2Rcmf4spo9F1kNrfY9knvkVUqy0+cN" +
				"PgVqFNEmc0loxEdcsVs0aUA3xxtIubeqdu/o+RP62cPQOi2PvBoTKv9ToR2TweeYdCCa" +
				"vp7USpj/jI+4Yvdw7d7zXLBQyovhy2r2uG5W6z0b2oMstmMGnwLzaeCdCZX9GK61kIjF" +
				"63d9wlqQ8sMFQ9vsVuDRhMp+Z2jPZPA5oi7ANxIq+1XgCmC/1Ryv+RP6VWzc3jTImpDy" +
				"w0HO7WoXPkNye3l9I7RrMvgc1gySGw3/rwkm+6K2eP2uT+GgZimfhq+qbRxtNbTJo6F9" +
				"SEIFyc4gM/hkXDnwxYTK3ox7cSVmVe1eb7hSnjm5oF2uD+1EEr4U2jcZfP7KV4GuCZV9" +
				"DcktWFXU5lZVDHKlZin/Gpuau/q4q80agOkJld0ltG8y+LzO6UTjb5LwIHC3VZyMZTV7" +
				"PoyPuaQ08HFX+/wUWJ5Q2VeEdk4Gn7/4Gsnsb/IK8FmrNzk+5pLSw8dd7TYttBtxOz60" +
				"czL4ANGUv6SmQn8Hd15PjI+5pHTxcVe7PUVyA50/Abilj8EHgBtJZpGnPwOzrN4kf102" +
				"jsHHXFKa+Lir/b4W2o+4dQC+bvUafM4FLkio7K8Cuz3FkuNjLil93Ci43XaT3GDkC0K7" +
				"Z/ApYv+cULmPA3d4/SZn0aQB3Vy0UEqf+ob95XOrKrw22+eO0I5kqd0z+GTAKGBcQmVf" +
				"Q3IrcYq/DKL0MZeUPsPt9Wm3V0luevs4inwD02IOPjckVO7PgWVet8l6fMtLQ60FKZ0c" +
				"5xOLB4D7M9b+GXxS7L3A2ATKbQa+7PWaPH9RSl6fReDLoV2J29jQDhp8ish1CZW7kOSe" +
				"yyqYP6FfhdPYpXSbPb7c8NN+fwjtShL+yeBTPN4BfCCBcl8GZnqd5uzXpON7pPQavm7L" +
				"SwafeHw1tC9xGx/aQ4NPEfjHhMr9HvCc12jyHN8jZeE63XeOtRCL50P7kqX20OCTIm8F" +
				"PpZAuQ3AN7w+c+MZp7FLWbhOz7AWYvN1ktno+mOhXTT4FLAZCX3nfyeZlTZ1CK7fI6Vf" +
				"Y1NzV9fzic3W0M4kkQGuNfgUrnLgkgTK3QPc7HWZGw6YlDJjuL0+sbo5tDdxmxzaR4NP" +
				"AfosUJJAuf8GbPOazI3Q2+PAZikD6hteKbMWYrMttDdxKwnto8GnwJwIXJlAubuBW7we" +
				"cxl8Xj7dWpCywQHOsbuFZPaAvDK0kwafAnIZ8KYEyp0LbPdazOUvSNfvkbLCR12x204y" +
				"Y33eBFxq8Cms75jEnicvAd/2OswtV4SVsqOxqbnrokkDulkTsfp2aH/idk2RZIKi+JIX" +
				"ApUJlHsHzuTKqfkT+lVYC1KmDHf5idhtDe1P3CpDe2nwKQBJDNp6BfiW119u1TfsL8OB" +
				"zVKmuPxEIr4V2qEstJcGnxyrJJntKRYCtV57ueUS+FL2NDS96qOu+NUCdyZQ7gdI5gmJ" +
				"wSeHpibwHQ9gb48kHRN7fBJzU2iP4s4EUw0+2XUi0WyuuP0KWO81l3tOjZWyp7Gpuau1" +
				"kIj1oT2K22UU+NT2Qg4+nyCZKey3er1J0rFxSnuikmiP3hTaT4NPBiXRXZdUwpY3UKkg" +
				"2eOTqKSeQBT0465CDT6DgZEJlPtt4n+mKm+gUkFzKYrEHCCZ9eRGhnbU4JMhf5dAmS8C" +
				"C7zO8sNF0KTMGh6WolAyFoT2KQvtqMEnIccDn06g3B+QzGqZOgbPuDmpJB3KSySzoOGn" +
				"SWZjb4NPAi4CTo65zGbge15fktR69Q37fdSVrHmhnYrTyaE9NfhkwOUJlLkUeNZrS5La" +
				"Enxe8VFXsp4FfpFAuQX5uKvQgs/JwAUJlPtdr6v8chE0Scp5O3UB8T9BMfjE7BNAp5jL" +
				"fC6hJK1WcNl7STqipaG9ilMn4JMGn3RLYlDzfOJ/dipJUpyagR8mUO4lBp/0qgRGJHAi" +
				"zfd6kqS2+7PT2XMliR/qIyiwjUsLKfgkkUofAJ73WpKktqtv2F9uLeRELbAsgXI/XUiV" +
				"VEjBZ1ICZf7A60iSlCFJtFsTDT7pMxQ4PeYytwOLvYYkSRmyOLRfcTo9tLMGnxSZkECZ" +
				"PwNe9hqSJGVIE3B3RtpZg087fDyBMt2XS5KURXdmpJ01+LTRECDuxe2eB37rtSNJyqDf" +
				"Ev+aPoNCe2vwSYGPJVDmAuCA144kKYMOAAsTKLcgHncZfA7tTq8bSYrH2WWdH7MWci6J" +
				"duyjBp/8Ow04O+Yy/wCs95qRJGXY+tCexeltod01+OTRhQmUucjrRZJUAJJozy7MeqVk" +
				"Pfh8OIEyf+a1kj6n9Tphg7UgSXlvz6oMPvnTA3hfzGWux8dcqdS1pOMea0GS8t6mjQ7t" +
				"r8EnDz4AHB9zmf/ldSJJ8RpSduJaayFv4u71OT60vwafPEjiOeNir5F0Ko16fNZYE5LU" +
				"KksSKPMig0/udQDGxVxmLeCUy5SatmSzY3ykbPIHS349Gtq3OI0L7bDBJ4feBrw55jLv" +
				"x0ULJSl21y6t81FXft0fc3nloR02+OTQBQmUucRrI90G9iqx10eSWu/ejLTDBp8jiHtg" +
				"VQPwoNdGupU6s0vyB4vaYkVo59LcDht8juBEYFTMZT4AvOy1kW59SzvVWQuSP1jUai+H" +
				"di5O7w3tscEnB0YmUNm/9LpIv5NLO22xFqRsGdirpMZaSIW427nOwLkGn9w4LwMnhBLQ" +
				"t/R4g4+UMS4+WrDBB2CMwSc3RsdcXg3wrNdEFoJPp804NVbKFLebSY1ngadT3h4bfA6h" +
				"M/CumMv8lddDNjglVsqcNX1LO/3JakiNuNu7d5HBcT5ZCz7vBk6IuUwfc2WIA5ylbHHx" +
				"0VSJu707gfg7Iww+bxD3pqSvAg95LWQq+PjrUcoIp7Knzm9CuxenMQafZL0n5vKqgZ1e" +
				"C9lxdllntxWRMuI0g0/a7AztXpwyN7OrY8Y+64iYy/y110HWbqQOlJSywiUoUmlFzOWN" +
				"yFiWyNSHPRPokfITQAkb2KvkaZzZJWXBmiFlJzohIX3i/sHfI7TPBp8EvDvm8pqBlV4D" +
				"2XLZok2bu5Z0bLQmpPRzJmYq/Sa0f2lunw0+wciYy3sc2OE1kD2n9Sp5ylqQ0s2Bzam1" +
				"M7R/cXpPliqgmHt8fuf5n00OcJYy8QPF4JNecbd/mRrgnJXgU0r8zxANPhkVxg04zkdK" +
				"9Q+UE6uthaIJPqeHdtrgE6OhCXzWVZ772eS4ASn11gwp6+x1ml5xt38dQztt8InRO2Iu" +
				"bztgN2yGeVOV0qtvaae6yxZt2mxNpNaG0A6muZ0u+uBzTszlPQIc8NzPLsf5SP4wUZsd" +
				"CO2gwaeIgs9qz/tsO7d/1xU4zkdKpZH9u7oVUPr9Pubyhhp84tMZOCvmMqs957Nt2pLN" +
				"G1zPR0olx/dkw6Mxl3dWaK8NPjE4A+iU8gOuPDi3f5cHrQUpXYaUdV474c7n91gTRRd8" +
				"OpGRFZyzEHzi7u15Eaj1nM8+p8tK6eNjrsyoDe1hmtvrog0+b4u5PAfFFojQ4+M4Hyk9" +
				"1ozs38Xgkx1JPO4y+MRgcMzl2UtQICbc+fweb7JSegzsVbLBaeyZEnd7aPBJaUX+wXO9" +
				"cNitLqXHuMpu91sLmRJ3e/i2LHzptAefLsCpMZf5hOd64fBxl5QaPubKnvUxlzcA6Grw" +
				"aZ9BMX/GZuBJz/XC4eMuKR18zJVJT4Z2Mc5McbrBp33eGnN5zwJ7PdcLS3jcZa+PlEc+" +
				"5sqkvaFdjJPBp50qYy7Px1wFaM7KrUtczFDKqzXjKkvvsxoyKe52sTLtXzgLj7ri9JTn" +
				"eGFyMUMpf0b27/KQixZm1h8NPukyMObynvEcL0wXD+7xE3zcJeXDmnGV3eztya6amMvz" +
				"UVc7nRZzeRs8xwvTtCWbNwzsVeLxlXKsb2mnulnL61dYE5n1dMrb7aIKPp2B8pjLtMen" +
				"gF08uMdPsddHyqnzK0sd1Jxtcff4vJmUb1aa5uDTP+byXgJe8BwvXA5ylnJujbO5Mu8F" +
				"YF/K2++iCT79Yi5vI3DAc7ywXTy4+13WgpQb4ypL73Ptnsw7QPxPQww+Kam45z2/i+FG" +
				"3O1+fNwl5cKaMKlA2Rd3+9gvzV+2mIJPred24bts0abNriciJW9IWee105ZsdkJBYYi7" +
				"fbTHJyWJcZPndnGYPPSkO7DXR0rSmslDT/q+1VAw4m4fDT5tdErKE61S6rJFmza7f5eU" +
				"nCFlnddeu7RurTVRMOJuH09J85dNc/Dpm/JEqxS7eHCPu7DXR0qCvT0Gn6M52eDTNmUx" +
				"l+fMgyJy7dK6tUPKOvuLVIqZvT0FKe72sSzNX7Zjij/Xm2Iu80+e28Vl6ojet2KvjxQn" +
				"e3sKU13M5fVJcb5I7Qd7E9ApxvIagb2e28Vl2pLNG5zhJcXH3p6CtTe0k3E5jvg7Lwo+" +
				"+MT9fLDO87o4OcNLio29PYUt7nYytY+70hp84q6wrZ7TxemyRZs2Xzy4+93WhNQ+I/t3" +
				"ecjenoIWdzuZ2gHOaQ0+PVOeZJUhlww96fauJR1XWBNSm60JY+ZUuLbEXN5JBp/8Vtg2" +
				"z+niNeHO5/dcMvSk2/GRl9QmFw/ufrd7chW8uNvJngaf/FbYTs/p4jZv9ba7+pZ2sudP" +
				"aqWuJR1XhB8OKmw7DD6FFXx2eE5r+qg+s7DXR2qNNVNH9L51wp3P77EqCl7cHQQGn1bq" +
				"ZfBR3K5dWrfWrSykYzekrPPaOSu3LrEmikLc7WSvtH5Re3xUVK4Z1ecGBzpLx2TN9FF9" +
				"brQaDD5t1MPg0zrdYi5vp+e0IBro7IrO0tFDz+ShPb/vgOaiEnc72d3g0zonxlxeo+e0" +
				"WsxZuXWJ+3hJhzewV8mGhdU7HdBcXBpS3o4XfPA5IeUHVBk3fVSfG33kJR3SmmuiiQAq" +
				"LnF3EJyQ1i+a1uATdxfZy57TOthlizZt9pGX9NehZ/LQnt+ftmTzBqui6MTdTvqoq5U6" +
				"pzzJqgDMWbl1ibO8pNcMKeu81kdcRctHXQYfFYNrRvW5oW9pJ6frquh1Lem4wllcRc1H" +
				"XXkWdxfZfs9pHcqEO5/f48KGEmuuGdXnBmdxFbW420kfdeXZbs9pHc61S+vWTh7a8/uG" +
				"HxVr6BlXWXrfrOX1K6yKolY0k4CKJfgc8JzWkSys3nm7U9xVjAb2KtmwrKbBWVx61eAj" +
				"FZmZY/vOcLyPiknXko4rZo7te601oWKS1uDT1UOjXJtw5/N7Zo7t+yXX91GRWDNzbN8v" +
				"Oq5HCemW1g+W1uDTKcayXvH807GatmTzBtf3UTGEnqkjet967dI6H+/qYHGu5ZPaJ0rF" +
				"8Khrr+eyWmPOyq1LHOysQg494ypL75u3ettdVoXeYF8xfMliCD5dPJfVWgurd94+rrL0" +
				"PsOPCs2Qss5rHcysw+hcDF8yrcEnzvUEjvdcVlssq2mYNbBXiUv3q2AM7FWycObYvjOs" +
				"CR1GnIsOpnY2dVqDjystKxVuGl9+1cBeJQutCWVd15KOK24aX37VhDuf32NtKAdSu36e" +
				"09mlI5hw5/N7bhpffpUzvVQAoWeqoUcqnuDTwUOtdoafqYYfZTn0uOO6juI4g09h6e45" +
				"rfaYtmTzBsOPDD0qYKUGn/yK+9lgJ89pGX5UZNZcM6rPDYYe5amddIxPK8W9loArQcvw" +
				"o6IKPdNH9bnRjUeVx3by5bR+UYOPZPhRIbVeJR1XzB5fftWclVvdd06tEfejrpcMPq0T" +
				"dxfZCZ7TMvyoGELPTePLp7oVhVLQTvqoq5Xi7iIr9ZxWUuHHHd2VptDjmB619RRKeTte" +
				"8MHnpZQfUOkv4WduVcUlLnKofOpb2mmJoUcpayd91NVKcS+y1dNzWklpWeRwSFnn7+He" +
				"Xsqxgb1KFs6tqrjE0KN2Oinm8nzU1Uo7U35Apb8KP+u27LvKjU2VQ2tG9u9yi9tQKKXt" +
				"5C6DT+tsN/goi5bVNMyaOqL3rYYfJR16xlWW3reqdu8XDT1KaTu5Pa1f1B4fKWbzVm+7" +
				"a+bYvjOc8aWkQs/0UX1uXFbTMMuqUIx6prwdN/jk+YBKRzRref2Km8aXT3XQs+LUtaTj" +
				"irlVFZe4Ro8SEHcHgcGnlXbEXF5vz2nlWpjuftXI/l1uwUdfap81Q8o6f+9HE/pVOYhZ" +
				"CYm7nTT45LnCyj2nlQ8T7nx+z6ravV903I/aE3omD+35/XVb9jmIWUkqi7m8HWn9omkN" +
				"PvUxl9fHc1r5NG/1trvmVlVc4mKHao2W7ScWVu+83dpQwuJuJ/9s8Mlv8LHHR3nXstjh" +
				"uMrS67H3R0e2ZmT/Lrf8aEK/KrefUI7E3U5uMfi0zovAq3H+cAK6eF4r3ybc+fyeZTUN" +
				"s5z1pcPerEo6rpg6ovetTlVXDnUh3pWbXw3tuMGnFZqBrSlPs1KbzVpev+JHE/pVOfBZ" +
				"B1kzpKzz9+ZWVVwyb/W2u6wO5VDc7eOLoR03+LRS3N1kp3huK01aBj7PHNt3hmN/ilvX" +
				"ko4rpo/qc+O6LfuuumzRps3WiHKsIuby6tL8ZdMcfOIe59PPc1tpNGt5/Yq5VRWXXDy4" +
				"+xex96fYrBlXWXr9jyb0q3JtHuVR/5jL25rmL9spxZ/tBYOPikUYy3HL3KqK/5m3etvV" +
				"67bsGwYMt2YKN/AM7FWyYeqI3rdeu7Ru7bKaBmtEhRR8NqX5y6a5x2dTyg+sFLtpSzZv" +
				"WLdl31XTR/W50cdfhall8PLG7U2XOGNLKRF3x0CtwScdFWfwUWbMWbl1ydyqiksmD+05" +
				"1dlfBWPN5KE9p/5oQr8qBy8rZYqqxyfNj7oMPipq4fHX7YsmDbhrQfWOKYvX7/4kPv7K" +
				"ZOAZV1l63+ShJ91x2aJNmxdW77RGlDYDUt5+F03wiTsxngZ0AA54jiuDAeiW+RP6/WRh" +
				"9Y7Ll9U0XGQAyl7gcRyPUqpDaB+LJvh0OHAgfTlg2E2PAHQGXoq56P6kvAtOOpr5E/pV" +
				"GICyE3isDqVcvwSCShfgpbUz3pXKL5zmHp99RGsBxLmw0mkGH2VdaExnLZo04NZ71u+a" +
				"uHj97omNTc1jrJn86lrSccW5/bs8aA+PMqYy5vLqiL/TomiCD8DGmIPPIGCF57kKwcFj" +
				"gB6u3Xvewuodl9c37C/HXqBcWtO3tFPd+ZWl9390cI+7wpYk1oqy5PSYy6tJ+xdOe/B5" +
				"BnhPjOWd5jmuAg1AS4Als8eXD1u8ftfEVbV7RxuAkg08Q8o6r714cI+7Zy2vX7GweicO" +
				"WlZGxd3jY/Bppw0xl3eG57gKWVgXZu38Cf0qVtXuHb14/a5P2QsUX9hp6d0ZV9nt/ssW" +
				"bdq8bss+a0VZ99aYy3va4JOu5DjYc1zFIIwDugu4a25VxaBlNXs+vKym4aLGpuauhqDW" +
				"hZ2uJR0bz+3f5cHzK7vdf+3SurX27qjAnBVzec+k/QuneVYXwFDgsRiLbga6AXs911WM" +
				"Zo7tO2ZVbePodVv2DbMn6OhhZ2T/rg/NWl6/wipRgeoC7CHexYzPAaoB0jqrK+3Bpyuw" +
				"O+aD8k7AZeJV9OZWVQx6uLZxzKravaM3bm8aVOQhaM3AXiUbhpR1fmxk/64r3EpCRWIY" +
				"8PuYOxe6A41pDj5pf9TVCDwHDIyxzMEGHynaF4xoHN3tiyYN6PZw7d7zHt/y0tAi6Q1a" +
				"07e0U92Qss5rzy47sXpIWee1ly3atHnj9iYWr9/tyaFiEffwj+dbQk+adcrAgflDzMHn" +
				"bM916fUOnhkG0SKJG7c3nb5uy0vDNm5vqgy7xZPRMLQGoKVHZ2CvE55uCTrLahpw+rmK" +
				"2NtiLu+JLHzpLASf9UBVjOW93XNdOrIwOHozB617NbeqYtAz25vOqG94pezxLfvOqW/Y" +
				"/+bQM5SWQLQGoGtJx8bTepU8NbBXSc3AXic83be00+Zrl9at3bi9iY3bmzy40muGJtBR" +
				"YfBJYUW+w3Ndar2DHo29zuzx5cMam5q7PbP95UEAj2/Zdw7AG4JRe8PRmpZ/aAk2AAN7" +
				"ldR0Lem457ReJ2zoWtJxz7VL69Y2NjWzbss+nGou5bw9XG/wiUfcXWdvItqzq9ZzXmq/" +
				"gwYCrzjcfzN/Qr+K+ob9ZW19j76lnba07HvVEmwAw43Udv1Dexgne3xi8hSwP+bPeo7B" +
				"R8qdgx6dSUqHuHt79gNPZuGLd8zAZ9xH/L0+53jOS5KK2NCYy3sytNcGn5hUx1zeCM95" +
				"SVIRi7sdfDQrXzwrwSfuCn0X0MHzXpJUhDqEdtDgU0TBpxcwyHO/+Myf0K/i4sHdr+lb" +
				"2unemWP7jrFGpNebW1XhvbHwDQrtYFEGn04Z+ZzVREthxxnURgJ/9PwvDtNH9alavH7X" +
				"Jy5btOkvWzPMWl5ffvHg7ncvXr/7FmtIgqkjek+ctmTz1X1LO9WN7N/loYsH9/hJy2w6" +
				"FZSRMZfXDPxfVr58Vnp8GhIIKe/23C9sLb07XUs6Pjhn5dbrNm5vmszr15IZvnj97k8O" +
				"Ket826JJA7pZYypWiyYN6Dayf5eb563edjUwvL5hf9Xi9btvvmzRpntG9u9y8+zx5cOs" +
				"pYISd/v3NNFmp5nQKUMH6mHgTIOPjmb2+PJhD9TsufCyRZsu4uiL5g1ft2Xf8EsXbTpj" +
				"9vjyL7o5pYrN3KqKQdOWbP5WfcP+Q62QP3xV7d7hq2r3ju5b2qlu8tCT7pizcusSa83g" +
				"8warsvTl0747+8EuB74f49s0Ey3etMNroHACz8LqHVeEfaXaskrwmslDe35/YfXO261N" +
				"FYOpI3pPbOnlOdZrpGtJx8aLB3e/66ODe9wV9nhTtvQEXgSOi/NUAv7qvpnW3dk7Zuhg" +
				"/S6B7z7Ka6AwAs+Qss63Xbu07rZ1W/ZdSdu3Rhi+sHrnFQN7lSyYP6FfhTWrQrVo0oBu" +
				"Q8o639bK0AMwvLGpeczC6p3zLl20acnkoT2n+Jg4c94bc+gB+G2WKiBLPT4dge1Ajxjf" +
				"ag5wjddBdgNPO3t4DqtrSccVlww96fZ5q7fdZU2rkMwc23fMLSu3Xt/Y1DwmrmvFHqBM" +
				"uTnmdm8X0Qyx5jf+D2nt8clS8AH4FTAuxrdaC7zT6yBb5k/oVzFn5dbrkgg8b7BmZP8u" +
				"D10zqs8N3tCVdYsmDeg2b/W2q5fVNFyUxHXjj4XM+D0Q52D1ZcAHDtnA+qgrFg/HXN5Q" +
				"ouedysiNe1xl6czLFm26p52PtI7V8FW1e6+5dNGmJa75oyybPb582LQlmxcsq2m4Ianr" +
				"prGpecy81duudo2sVOtB/FtVPJy1Sshaj88Y4MGY3+4jgLMUUm7y0J5TFq/fPTGu7vk2" +
				"WDOyf5eHpo7ofavrmihLPxaS7OU50vUypKzz2qkjet86bcnmDR6J1PhwAu3decCKQ/0P" +
				"9vjE43fAyzGX+QGvhXT/Uu1b2unehdU7r8hj6IHQ+zNtyeYFU0f0nuiRUdrNHNt3zKWL" +
				"Ni1JspfnSNfLui37rpy2ZPOCiwd3v8YB0KlxQczlvQw8krVKyFrw2ZdAJRt8UvpLdVxl" +
				"6cxrl9bdFtYXGZ6Gz9XSnT+krPNtLu2vNJo/oV/FkLLOt81aXn9Tnn8sQLRI6M0+Lk6N" +
				"uNu71cBLBp/kPRRzeacDp3o9+EvVX7PK+o+FyUN7TsnhGLhW/WCYtbz+piFlnW9zqYi8" +
				"OTW0d3H6dRYrIovBZ0UCZV7gNZGOG/fI/l1uTskv1Vb9mp0+qk+VR1D5/LEwbcnmBQur" +
				"d85L6Y+F1/1g8HFxXiTRzhl8cuRhokdeBp8Cu3FfumjTklW1e69J8Y37sL9m56zcet3A" +
				"XiUL3NNIuTS3qmJQy2Otw2w5kcrrpeVxsb0/mQ4++8jYwoUtsjarq0Xc6/k0EG1f8bLX" +
				"Rm4tmjSg2y0rt16/qnbv6KwFnsNYM6Ss89rpo/rc6OwvJWX+hH4VC6t3XJ6H2Vqx6lrS" +
				"ccU1o/rcMGt5/QqPaqJOINqmojTGMg+7fk8LZ3XF61cxl1dKNCVPOdSytkgWe3mOYPi6" +
				"LfuuvGzRpnvGVZbO9Bet4v6h0DKOJ8Vj4I5Zy9ifcZWlMx0rl6j3xRx6WoJPJmW1x+ds" +
				"YF3Mb3sb8Fmvj9yYPLTnlIXVO68ooMBzOGsuHtz97kuGnnS7qz+rPYHnnvW7JuZ5LatE" +
				"9S3ttGTm2L5fct2fRHwXuCrmMt9+tHbYLSviDT4dgM1AeYxvWwsM8PpI/gY+a3n9TTnY" +
				"biJV3M9IBp5j+6EwdUTvW932InbPA/1jLK8OqAAOGHxyF3wAfgT8v7jfGnjUayQZc6sq" +
				"Bs1YWjevSG7ghw1A5/bv8uDkoSfd4RggGXgOHX7GVZbeN3VE71v9kRCLcxJo134MXHq0" +
				"/yitwadThg/mfQkEn48YfJIxfVSfqmlLNl9HEfXyHEpjU/OYZTUNY5bVNFw0rrL0PgOQ" +
				"DtYyaPnSRZvOK+IfCMOX1TQMf2Z706D5E/pd6/URS7sWt59nuUKy3OPTA9gKHB/jW68H" +
				"zvI6ide4ytKZWZ99kuSv2yFlnddOHnrS969dWrfW6ihOs8eXD3ugZs+FXiev17Wk44qZ" +
				"Y/t+0WujXZ4ABsdY3itAH2DX0f5DH3XFH3wAHgDeH/PbnxUCkNqpWMfztDUA9S3tVDd5" +
				"6El3nNu/y4N28ReH6aP6VC1ev+sTG7c3DfIaOfy1MX1UnxvnrNzqZtKtNzgEnzgtP9Z2" +
				"1+nsyUjiQvi410r7hfE8t6Vt6fwUG17fsL9qzsqt9166aNOScZWlM90LrDDNn9Cv4uLB" +
				"3a/pWtLxwTkrt163cXvTZK+RI18bc1ZuvW5cZelMqyIV7dm9Wa+UrPf4nAbUxPz2fyCa" +
				"Lq/2hZ6iHsQc1y/dgb1KNlw8uMdP7QXKtkWTBnR7uHbveQ/U7PmgPaBtvx5G9u/y0DWj" +
				"+tzgtXDM/g8YEnOZlcAzx/If+qgrmeAD8Djwtpg/go+72mj6qD5Vc1ZuLfpBzEnc9MdV" +
				"lt43sn/Xh1zlNjtaxu48XLv3PH8IxGNgr5KFN40vv8rwc1RJPOZ6ojXtrbO6knNPAsFn" +
				"EnCd142hJ0WGL6tpGL6spmFN15KOjef27/Lg+ZXd7nfQZ/rMraoYtKxmz4dX1e4dfe3S" +
				"unKvh3ht3N40edqSzd3mVlW42OHR27G4/XchVEwh9PgMIerOi9NzwECOsjiTXlNEKzGn" +
				"yZq+pZ3qhpR1XmtPUHrCTn3DfsNODnQt6bjipvHlUw0/h27biR5HnRpzuUddrflgPupK" +
				"LvgA/BGIeyDoe4GVXj9H53T1dISglp6gs8tOrHZMULIWTRrQbd2WfcNW1TaODo+xunr+" +
				"G35SZBTwm5jL3AC8tTX/B4NPssHnRuArMX+M7xH/3iaGHuUsCA3sVbJhZP8uDw0pO3Gt" +
				"j8Tab25VxaCWsOMA5XSFH9f6+StJ7M31dVo5BMTgk2zwGQo8FvPH2E60F1iT15ChJ+sh" +
				"CGBk/y4PDexVssEg1Lqgs27LS8PWbdk3zF6ddJ/jrvXzFyXAn4DeMZd7DlBt8ElP8IGo" +
				"G+70mD/KJ4Gfeh0ZegoxCA0p67x2YK+SmiFlJ64d2Kvk6WLeGqDl0dUz218e9PiWfeeE" +
				"Hh08vw0/GfQJ4O6Yy3yaNgwnMfgkH3xuAOJe4OqXwHjvJ4aeYmg0upZ0bDytV8lTZ5d1" +
				"fqxv6fFbTutV8lQhjp2YW1UxqL5h/5tbQk59w/43OyDZ8FNAlgIXxFzmLOB6g0/6gk9l" +
				"SKVxaiYaFV/r/cTQU4yNCMDAXiUbSks67jm7rPNjpSXH7Wn59zSHovkT+lXUN+wvq2/Y" +
				"X1Hf8ErZxu1Ng+ob9peFrSHw/DX8FKj+wLPEvyvDoLa0rwaf5IMPwCPAiJg/zvUh7Rp6" +
				"DD16Qyhq6SUKAamma0nHPQBDyk78yxiiuEJSS5hp+feN25sGNTS92g3g8S37zgF4ZnvT" +
				"GWEsjuGmiBXxbK+vJtBerQbalGAMPrkJPp8DvhPzx3mOaGuMZkOPoUdtD0kx8fyT4efQ" +
				"OhJt4RT32j2fb2u7avDJTfA5GdhM/CtSXwj8vFhvIC5OKMnwk3ofAu6Pucz9QAXw50IK" +
				"Ph0L7MD/mWhActw+W6w3jumj+lQZeiRlUWNT85gZS+vmzZ/Qr6IIvm4S6879sq2hJ806" +
				"FuDB/0ECZX6Q+LsPMxF63HtLUtbDz6zl9bMXTRrQrYC/5luIenyy0J4afBJwXwIJtSMw" +
				"tZhuFnOrKgbNW73takOPpKzbuL1p8oyldbcVcPi5MoH2/M+hPTX4ZEAT8J8JlHs5cGKx" +
				"hJ4ZS+vmNTY1j/GWKalQwk/4MVdoSkL7FLcFFOjOBR0L9BxPonvuTcAlhX5zWDRpQLdb" +
				"Vm6daeiRVGiW1TRcNK6ydGaBfa1LQ/uUhXbU4JOg9cCqBMr9AtChkG8MM5bW3bZxe9Nk" +
				"b5GSCtDwZTUNF00f1aeqQL5Ph9Auxe13wBMGn+yZl0CZg4EPFGqFjassnXnQyraSVJDh" +
				"Z87KrdfNHl8+rAC+ywdCu5SF9tPgkwM/BbYlUG4hPiNm6ojeE12gUFKxhJ9Zy+tvLoBp" +
				"7km0R9uIf5NTg0+OvAT8MEMJO29mjy8f5gwuScWkAKa5J/UE4oeh/TT4ZNQ84t9qogPw" +
				"pUKpoPkT+lXMWl5/s6FHUrHZuL1p8i0rt16f0Y//JeIfc9pMgT/mKobgUwP8KoFyJxPt" +
				"gpt5s5bXz3YGl6Ritap27+ipI3pPzNjH7h/aobj9KrSbBp+Muy2BMo8Hrsl6xTiYWZIY" +
				"Pm/1tqszNtj5mtAOxe27xXDAiyH43JdQgv0M0CerlTJ9VJ8qBzNLUhR+Zi2vvzkj4336" +
				"hPYnbjXEv8mpwSdPmoHvJFDuiSSzfkLi3I5Ckl4vDHa+KQMf9fMks4vAd4h/TKzBJ4/u" +
				"AF5MoNy/B3plqSJcmVmSDm3dln3DJg/tOSXFH7EX8LkEyn0xtJNFoViCz17gewmU252M" +
				"jfWZt3rb1a7MLEmHNHxh9c4rUjze55rQ7sTte6GdNPgUmO+SzIZrnwN6Z6ECZo7tOyaM" +
				"65EkHSb8pHS8T2+S6e1pokgGNRdj8KkDFiZQbjfgi2n/8vMn9KsI61U4rkeSjqCxqXlM" +
				"Ctf3+WJob+K2MLSPBp8CNZtkBm/9PSmf4TVn5dbrHNcjSccmZev79AntTNyagZuK7dgW" +
				"W/D5I3BPAuWWAl9J65eeOqL3xHVb9g1DknSshi+o3jElJft5/VNoZ+J2D/CUwafw/UtC" +
				"5V4JDEjbl3XquiS1Tct+Xnn+GAOAqzLWHhp8UmYtyWxjcQIwK21f9paVW2caeiSpbTZu" +
				"bxqU5ynuN4T2JW6/Cu2hwadIfCOhci8B3paWLzl5aM8pbkkhSe0yfGH1zivmVlXk4176" +
				"NuDTCZV9Y7Ee0GINPr8GViRUn99MwxecW1UxaGH1ziuwt0eS2h1+Qu95rv1LQu30cuA3" +
				"Bp/ik9RUxQuB8/P95XzEJUnxycMjr/OBpNZdu76Yj2UxB5+HQupNwhzguHx9sakjek/0" +
				"EZckxWr4wuqdV+RoltdxwC0Jlb0MWGnwKV5Jpd6zgcvz8YXmT+hXsaB6xxTs7ZGk2MPP" +
				"nJVbr8vB+/wdMCShsv+52A9isQeflSQzwwvgaySzp8oRuVChJCVn3ZZ9wxJe2LB7aD+S" +
				"8EvgYYOPvgIcSKDck4Gv5vKLzBzbd4wLFUpSooYvqN4xJcG9vL4C9E2g3APAdR4+gw/A" +
				"74GfJVT254EzcvElFk0a0M2FCiUpeY1NzWPC/TZuZwBXJ/SxfxraO4OPVQAhBe9PoNzj" +
				"gbm5+AILqndMqW/YX+WhlKTkLatpuGj2+PK4e9j/PbQbcdtPjp9AGHzS72ngPxIqeyzw" +
				"8SQ//PwJ/SoWr9/9SQ+jJOXM8Jh7fT4OvD+hz/ofoZ2Twed1vgbsTajsW0lmgzkgGtCM" +
				"j7gkKac2bm8aFNNA59LQTiRhL8kNljb4ZFwd8K2Eyq4g2m8ldg5olqS8iWug8/WhnUjC" +
				"zaF9k8HnkG4CNidU9ueBd8RdqAOaJSl/Yhjo/A6SG9C8ObRrMvgc1l7gnxIq+zii56yx" +
				"reg8eWjPKfUN+8s9bJKUP8tqGi5q4yamsbcLb/AVoNEjZPA5mgUkN+XvHUQ9P+22aNKA" +
				"bovX756IvT2SlG9tHeicyJOA4PfAjz00Bp9j0QxMT7D8WcCp7S1k3uptV7tCsySlw7ot" +
				"+4bNHNu3Nffkt5DQ2E+ixQqvJpnFeQ0+Beo3wN0Jld2VqGuzQ1sLmD+hX8WymoaLPEyS" +
				"lBqt6fXpAHyf5Gb73k2Rb0Rq8Gmba4CGhMp+PzClrf9nBzRLUvrUN+wvnz6qz7EsJDuF" +
				"5NbsaQC+6NEw+LTFZqLHUkn5Fm145DV7fPmwVbV7R3t4JCl1hs9bve3qo0xvP5Xklk4h" +
				"tFubPRQGn7b6NvBUQmV3ow2PvBZW77gCe3skKZUam5rH3LN+1+EWNewQ7vtJbXD6VGi3" +
				"ZPBps1eAzyZY/vuBq471P549vnyYixVKUrotXr974mF6faaR3CMuQnv1ikfA4NNeDwI/" +
				"SbD8b3GMO7jb2yNJ6XeYXp8zgNkJvu1PQnslg08sPg9sT6jsLkRrB5Uc6T+yt0eSsuMN" +
				"vT4l4T7fJaG32wF8wVo3+MTpz8CMBMsfxlHWc7C3R5Ky4w29PjeE+3xSvgTUW+sGn7j9" +
				"APh1wifuIWdr2dsjSdmzeP3uiWWlnT4Y7u9J+XVon2Twid0BYCrwckLlHwf8J9D7jf+D" +
				"vT2SlD2NTc1jtu19dSHJ7cX1cmiXXKHZ4JOYPwJfS7D8/sAPOWiKu709kpRdrzQfOCnB" +
				"4m8M7ZIMPomaDaxNsPwPA//Q8i/29kiSDmEt8E2rweCTC/uBvwWaEnyPm4B32tsjSTqE" +
				"ptAO7bcqDD658jjJ7aoL0dTHu+c/un0a9vZIkl5vVmiHZPDJqZtI9pHXwCf//PJHrWZJ" +
				"0kHWkuxCiAYfHdZ+4DJgX4Lv0dNqliQF+0K74yMug0/e/AH4stUgScqBL4d2RwafvPoO" +
				"sMxqkCQl6IHQ3sjgk3cHiEbXb7cqJEkJ2E70iMuFCg0+qbGZaPVMSZLiNjW0MzL4pMoi" +
				"4A6rQZIUoztC+yKDTyr9A/Ck1SBJisGTHLSSvww+abQX+Hj4U5Kk9rQnn7A9MfhkwRPA" +
				"1VaDJKkdrsap6wafDLkd+InVIElqg7tDOyKDT6ZMBZ6yGiRJrfBHYIrVYPDJot3A3wCN" +
				"VoUk6Rg0Ah8L7YcMPpm0HrjcapAkHYMrQrshg0+m3Q38q9UgSTqC7+DYUINPAZkB/NZq" +
				"kCQdwm+BL1kNBp9C0kQ03ucFq0KSdJAXQvvQZFUYfApNPfBRXIxKkhTZG9qFeqvC4FOo" +
				"fk80eM0ddiWpuB0APhPaBRl8CtpdwLesBkkqat8C7rQaDD7F4p+AJVaDJBWlJaEdkMGn" +
				"aLwKTAQesyokqahUh/v/q1aFwafY7AWqcKaXJBWLF4AP4yQXg0+RXwQfAvZYFZJU0BrC" +
				"/d4fuwafovc4cAl2e0pSoXoVmBzu9zL4iGig2+esBkkqSJ/DCS0GH/2V24CvWA2SVFC+" +
				"Gu7vMvjoEL7hBSJJBfWD9karweCjI7NLVJKyzyEMBh8do5Y1fh60KiQpkx7EtXoMPmqV" +
				"vcDFwCNWhSRlyiO4IbXBR22yG7gQpz9KUlY8DlwE7LIqDD5qm23ABUCNVSFJqVYT7tcv" +
				"WhUGH7VPHTAO2GRVSFIqbQr36TqrwuCjeDwHnIdLnUtS2rwQ7s/PWRUGH8XrmXBxbbYq" +
				"JCkVNof78jNWhcFHyagBxgJ/siokKa/+FO7HjsE0+ChhG4D3A1usCknKiy0h9GywKgw+" +
				"yo2ngPfhgGdJyrVN4f77R6vC4KPc2gCMBp61KiQpJ54N9117egw+ypPn/OUhSTnxx3C/" +
				"fc6qMPgovzYBY4AnrApJSsQT4T7r8AKDj1JiC1H3q3t7SVK8Hgn3VyeUGHyUMtuJZnv9" +
				"yqqQpFj8KtxXt1sVBh+lUyPwYeAnVoUktcvd4X7aaFUYfJRuTcBk4LtWhSS1yXeBSeF+" +
				"KoOPMqAZmAZ8BThgdUjSMTkQ7pvTwn1UBh9lzDeAT/urRZKOqincL79hVRh8lG0LgfHA" +
				"DqtCkg5pZ7hPLrQqDD4qDA8C7wVqrQpJep1aYFS4T8rgowLyBPAuYJVVIUkA/C7cF10A" +
				"1uCjAtWyo7DduZKK3Z3AebgwocFHBW8f0QC+63DGl6TicyDc/y4J90MZfFQkF/7XgY8D" +
				"DVaHpCLRAHwi3P/84WfwURH6L+Bc4BmrQlKBewZ4D7DIqjD4qLg9DgwHfmFVSCpQvwj3" +
				"uXVWhQw+gmiNn4uw+1dSYTlAtCDhRbiWmQw+eoNmogF/HyNazEuSsmxnuJ99BbefkMFH" +
				"R7AYeAfwmFUhKaOqiR5tLbYqZPDRsXiWaNDz7VaFpIy5HRgJ1FgVMvioNfYBU4nWunDK" +
				"u6S0awj3q6m4Po8MPmqHhcAwYK1VISml1ob7lKvSy+CjWGwgevR1Mw4SlJQeB8J96dxw" +
				"n5IMPopNE/Al4AKgzuqQlGdbwv3oS+H+JBl8lIgHgLcD96bws20CpgDHAx18+fLVrtfx" +
				"4XralMJr/V5gCLDMW7IMPsqFrcDFwN8Bu1P0ufoRzehYT7QRaycPldRqnYgGCa8P11O/" +
				"FH223cDl4f6z1UMlg49y7YfhV9fylH2u04EfA08Cfxt+uUo6euD523Dd/Ge4jtJkebjf" +
				"/MBDJYOP8ul54HzgauCllH22ynCT/CPwGaDEwyX9lZJwfWwI10tlyj7fS+H+Mi7cbySD" +
				"j/LuAPBtorE/D6Xw851K1GX/LPBFoLuHTKJ7uB42huvj1BR+xofCfeXbOKNUBh+l0NPA" +
				"GOCzpGvsT4s3A98CaoFvAuUeMhWhsnD+Px+uh4oUfsbd4T4yJtxXJIOPUusAcBvwNuAX" +
				"Kf2MPYBriXqAfgAM9bCpCLwduAN4Lpz/PVP6OX8BnB3uIwc8bDL4KCs2AR8CJhOtt5FG" +
				"JxAN5nwMWEG0k/NxHjoVkOPCeb2CaOPOvwvnfRptCfeLDxH1ykoGH2XSncCZwHdJ9zP6" +
				"9wH/RbSx4bXAyR46ZdjJ4TyuCef1+1L8WZuJenfODPcLyeCjzNsJTAPeDTya8s/6FqLx" +
				"D7XAXURjDDp4CJUBHcL5ehevjWN7S8o/86PhvvDZcJ+QDD4qKGuAdwGfy8BN7gTgU8CD" +
				"RAu5XY29QEqnk8P5uT6cr58ivY+zDv4x9LlwP1jjIZTBR4VsP/DvRIujzSMbU1TPAOYA" +
				"LwA/Ay7CRRGVX8eH8/Cn4bycE87TtGsO1/3p4T6w30Mpg4+KxYvAlcA7gd9kqLGZAPxP" +
				"aGxuBUZ4KJVDI8J590I4Dz+eoRC+MlzvV4brXzL4qCg9RjTwchLZWpX1ZOALwCNE64x8" +
				"DRjs4VQCBofz6+lwvn2BbD12rQ3X9+hwvUsGHxW9A0QDMgcRrSS7M2OfvxK4DniCaMrw" +
				"dUQzVKS2OhP4p3A+PRHOqcqMfYed4Xo+PVzfrskjg4/0Bk3ALeFGeUv496x5e/h1vj68" +
				"vgac46HVMTjnDefO18P5lMXreE7Gr2MZfKScejH8UhwMLCC7e/ScGX6pP0q0Wu5c4INA" +
				"Zw+xwnnwwXBePBfOkyz3FjaH63UwcA2O45HBR2q1Z4BPA0OAe8h2V/kAorVKfg5sA5YQ" +
				"DfI81cNcVE4Nx31JOA9+Hs6LARn+TgfC9fn2cL0+42FWmnWyCpQBTxAtuz+cqPt/XMa/" +
				"Txfgw+HVEvCWAQ8QrcOy3UNeMHoB5wHnh1dlgX2/ZcBXcC0eGXykRKwBPgCMInokcEGB" +
				"fK/TwutK4FWimS+/AX4N/BYfGWTJm4D3EM1UfC/RuJ1C3P/tl8CNRFPUJYOPlLCVwHii" +
				"pe6vAy4soO92HNFaJ+8kWo33ANFA14eAh3lt+rzS4XSi1YfPJZquPZjC3uLk50QDsH/n" +
				"oZfBR8q93xGtXjsM+CrRo6NCG7fWATgrvK4Kf/cisJqoB+z3RD1Emz0dEldB1IPzTqLH" +
				"rsOBPkXwvZuJFkv8GrDW00AGHyn/1gIXE82GuYZogGVJAX/fNwEfCq8WW4nWfHks/Pk4" +
				"sAGnErdFCdGaUmcDQ0PYGVokIedgTcB/Ek1Jf9LTQgYfKX2eBK4AZgKfJxoz071Ivnsf" +
				"okHfBw/83g9sDCHoKaJB4k8DNbgTNkQDjyuJxledRbTX1dvCvxfzvXE30X5a3wb+5Gki" +
				"g4+Ufn8CriWaAfYZol2gBxTp9T0ovN5oawhFG4FnifZ+2kS0vcALFMbMsl7AKUB/oF/4" +
				"54Eh7AwM/7te8zzwb8B/hPAjGXykDP5yvSX8cv1YCEDvtVqAqIeoD9HA3EPZGwLQVuDP" +
				"QF34561EY4x2HuL1coKf9wSg5yFebzrou5QT7WHVJ4ScLh7mY/KbEHj+m2hWoWTwkTLu" +
				"VeBn4TWUaMG4iUCpVXNYXTh8b9GR7CB6xLYH2Ae8FP7+FaDhCP+/Ul7bZfxEolWNu4V7" +
				"1Ekejtg1EO2f9V2iMWGSwUcqUNXAFOBLwGRgKtHK0IpHS0jpY1Wk0jqi8TsLgV1Wh4qR" +
				"W1aoWO0Kv3bfTrTg3I95rXdCKiQvhfP7PeF8/66hRwYfqbg9DFxKNEZkKrDKKlEBWBXO" +
				"5/Jwfj9slUgGH+lgu4DbiVbhPROYjdN5lS1/CuftmeE8vh17dySDj3QMngK+TDQV+v3A" +
				"HUQDd6W02RnOz/eH8/XL4fyVZPCRWu1VYDnRwojlRCtE343jgZRfL4Xz8KNAWTg/l+N0" +
				"dOmonNUlHbuXgXvDqyvRlhF/A3yQ4lkhWvmzG/gF8F9Em4U2WiWSwUfKlUZeWxvoBOD8" +
				"EIKqgN5Wj2KyDVgSws4DJLtIpGTwkXRMXgbuD6/jiFZDvgi4ENcIUuutC+fSfcAj+PhK" +
				"MvhIKfYq0bThh4F/Itoj6kJgPDCWaDVi6WB7iMbnLA2BZ5NVIhl8pKzaBHwvvDoR9Qad" +
				"H17v9hosSvuJenKWET2+eiT8nSSDj1RwDd5vw+sGot6f0eH1XuCdvLZflQrHK8DviTYD" +
				"fSi89lgtksFHKjZ7eG1sEEQbg747BKH3ACNwtlgW7QZWh4D7EFGPjjOwJIOPpDfYSzTW" +
				"Y3n4945EK/C+66DX24gGUCsdXgX+EMJNy+tJoNmqkQw+klqnGXgivH4Q/q4LcDYwFDgn" +
				"/Hl2+HslH0wfB6qBx8Kfj4e/l2TwkZRQ49vSs9DiOOB04CyiHqK3AWeE1wlWWau9TLTl" +
				"w1MhdK4Pfz6NU8slg4+kvHv1oIaaNwSiU0MoqgQGhn8+Lfx9MYeil4HngJrweib8+TTw" +
				"rAFHMvhIymYgamnY36gj0R5P/YFTwmtA+LMc6BP+zOK6Q3uAOmBr+PMF4Pnw5wtALbAF" +
				"x+FIBh9JRaMZ+FN4HUnnEILeTLQVR8/DvHqE/7ZreJUAJ4a/O/h+0+0wQeXgdWz2EW3C" +
				"2UQ0G6ox/N0uop3ID/XaFr7L1vDfStIhdThw4IC1IEmSikJHq0CSJBl8JEmSDD6SJEkG" +
				"H0mSJIOPJEmSwUeSJMngI0mSZPCRJEky+EiSJBl8JEmSDD6SJMngI0mSZPCRJEky+EiS" +
				"JBl8JEmS0uT/DwBJiXzj1S0Q6QAAAABJRU5ErkJggg==";
	}

}
