-- admin_level_students_progress_view.sql 1.2.0 29/04/2017
-- Copyright (c) 2016, Fatec-Jessen Vidal. All rights reserved.
-- Fatec-Jessen Vidal proprietary/confidential. Use is subject to license terms.

DROP VIEW IF EXISTS ADMIN_LEVEL_STUDENTS_PROGRESS_VIEW;

CREATE OR REPLACE VIEW ADMIN_LEVEL_STUDENTS_PROGRESS_VIEW AS
	SELECT
		SUBSTR(S.STU_RA, 7, 3) AS YEAR_SEMESTER,
		INSTITUTION.INS_CODE,
		INSTITUTION.INS_LEVEL AS LEVEL,
		INSTITUTION.INS_COMPANY AS INSTITUTION,
		(SELECT COUNT(*) FROM STUDENT 
			WHERE STU_IS_COMPLETED = 0 AND INS_CODE = INSTITUTION.INS_CODE
			AND SUBSTR(STU_RA, 7, 3) = SUBSTR(S.STU_RA, 7, 3) GROUP BY INS_CODE) AS NOT_FINALIZED,
		(SELECT COUNT(*) FROM STUDENT
			WHERE STU_IS_COMPLETED = 1 AND INS_CODE = INSTITUTION.INS_CODE
			AND SUBSTR(STU_RA, 7, 3) = SUBSTR(S.STU_RA, 7, 3) GROUP BY INS_CODE) AS FINALIZED,
	
		COUNT(*) AS TOTAL
	
	FROM STUDENT S INNER JOIN INSTITUTION ON S.INS_CODE = INSTITUTION.INS_CODE
	GROUP BY YEAR_SEMESTER, INSTITUTION.INS_CODE, INSTITUTION.INS_LEVEL, INSTITUTION.INS_COMPANY;
	