-- csv_report_view.sql 1.2.0 29/04/2017
-- Copyright (c) 2016, Fatec-Jessen Vidal. All rights reserved.
-- Fatec-Jessen Vidal proprietary/confidential. Use is subject to license terms.

DROP VIEW IF EXISTS CSV_REPORT_VIEW;

CREATE OR REPLACE VIEW CSV_REPORT_VIEW AS
	SELECT	USER.USE_ID AS STUDENT_ID,
    		STUDENT.STU_RA AS STUDENT_RA,
    		USER.USE_NAME AS STUDENT_NAME,
    		COURSE.CRS_CODE AS COURSE_CODE,
    		COURSE.CRS_NAME AS COURSE,
    		INSTITUTION.INS_CODE AS INSTITUTION_CODE,
    		INSTITUTION.INS_COMPANY AS INSTITUTION,
    		INSTITUTION.INS_LEVEL AS INSTITUTION_LEVEL,
    		CONCAT('20', SUBSTR(STUDENT.STU_RA, 7, 2), '/', SUBSTR(STUDENT.STU_RA, 9, 1)) YEAR_SEMESTER
	FROM STUDENT INNER JOIN USER ON STUDENT.USE_ID = USER.USE_ID
				 INNER JOIN COURSE ON STUDENT.CRS_CODE = COURSE.CRS_CODE
	             INNER JOIN INSTITUTION ON STUDENT.INS_CODE = INSTITUTION.INS_CODE
	WHERE STUDENT.STU_IS_COMPLETED = TRUE
	ORDER BY YEAR_SEMESTER DESC, STUDENT_RA;